# coding: utf-8

"""
    PTV Timetable API - Version 3

    The PTV Timetable API provides direct access to Public Transport Victoria's public transport timetable data.    The API returns scheduled timetable, route and stop data for all metropolitan and regional train, tram and bus services in Victoria, including Night Network(Night Train and Night Tram data are included in metropolitan train and tram services data, respectively, whereas Night Bus is a separate route type).    The API also returns real-time data for metropolitan train, tram and bus services (where this data is made available to PTV), as well as disruption information, stop facility information, and access to myki ticket outlet data.    This Swagger is for Version 3 of the PTV Timetable API. By using this documentation you agree to comply with the licence and terms of service.    Train timetable data is updated daily, while the remaining data is updated weekly, taking into account any planned timetable changes (for example, due to holidays or planned disruptions). The PTV timetable API is the same API used by PTV for its apps. To access the most up to date data PTV has (including real-time data) you must use the API dynamically.    You can access the PTV Timetable API through a HTTP or HTTPS interface, as follows:        base URL / version number / API name / query string  The base URL is either:    *  http://timetableapi.ptv.vic.gov.au  or    *  https://timetableapi.ptv.vic.gov.au    The Swagger JSON file is available at http://timetableapi.ptv.vic.gov.au/swagger/docs/v3    Frequently asked questions are available on the PTV website at http://ptv.vic.gov.au/apifaq    Links to the following information are also provided on the PTV website at http://ptv.vic.gov.au/ptv-timetable-api/  * How to register for an API key and calculate a signature  * PTV Timetable API V2 to V3 Migration Guide  * PTV Timetable API Data Quality Statement    All information about how to use the API is in this documentation. PTV cannot provide technical support for the API.  

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.v3_disruption import V3Disruption
from typing import Optional, Set
from typing_extensions import Self

class V3Disruptions(BaseModel):
    """
    V3Disruptions
    """ # noqa: E501
    general: Optional[List[V3Disruption]] = Field(default=None, description="Subset of disruption information applicable to multiple route_types")
    metro_train: Optional[List[V3Disruption]] = Field(default=None, description="Subset of disruption information applicable to metropolitan train")
    metro_tram: Optional[List[V3Disruption]] = Field(default=None, description="Subset of disruption information applicable to metropolitan tram")
    metro_bus: Optional[List[V3Disruption]] = Field(default=None, description="Subset of disruption information applicable to metropolitan bus")
    regional_train: Optional[List[V3Disruption]] = Field(default=None, description="Subset of disruption information applicable to V/Line train")
    regional_coach: Optional[List[V3Disruption]] = Field(default=None, description="Subset of disruption information applicable to V/Line coach")
    regional_bus: Optional[List[V3Disruption]] = Field(default=None, description="Subset of disruption information applicable to regional bus")
    school_bus: Optional[List[V3Disruption]] = Field(default=None, description="Subset of disruption information applicable to school bus")
    telebus: Optional[List[V3Disruption]] = Field(default=None, description="Subset of disruption information applicable to telebus services")
    night_bus: Optional[List[V3Disruption]] = Field(default=None, description="Subset of disruption information applicable to night bus")
    ferry: Optional[List[V3Disruption]] = Field(default=None, description="Subset of disruption information applicable to ferry")
    interstate_train: Optional[List[V3Disruption]] = Field(default=None, description="Subset of disruption information applicable to interstate train")
    skybus: Optional[List[V3Disruption]] = Field(default=None, description="Subset of disruption information applicable to skybus")
    taxi: Optional[List[V3Disruption]] = Field(default=None, description="Subset of disruption information applicable to taxi")
    __properties: ClassVar[List[str]] = ["general", "metro_train", "metro_tram", "metro_bus", "regional_train", "regional_coach", "regional_bus", "school_bus", "telebus", "night_bus", "ferry", "interstate_train", "skybus", "taxi"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V3Disruptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in general (list)
        _items = []
        if self.general:
            for _item in self.general:
                if _item:
                    _items.append(_item.to_dict())
            _dict['general'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in metro_train (list)
        _items = []
        if self.metro_train:
            for _item in self.metro_train:
                if _item:
                    _items.append(_item.to_dict())
            _dict['metro_train'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in metro_tram (list)
        _items = []
        if self.metro_tram:
            for _item in self.metro_tram:
                if _item:
                    _items.append(_item.to_dict())
            _dict['metro_tram'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in metro_bus (list)
        _items = []
        if self.metro_bus:
            for _item in self.metro_bus:
                if _item:
                    _items.append(_item.to_dict())
            _dict['metro_bus'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in regional_train (list)
        _items = []
        if self.regional_train:
            for _item in self.regional_train:
                if _item:
                    _items.append(_item.to_dict())
            _dict['regional_train'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in regional_coach (list)
        _items = []
        if self.regional_coach:
            for _item in self.regional_coach:
                if _item:
                    _items.append(_item.to_dict())
            _dict['regional_coach'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in regional_bus (list)
        _items = []
        if self.regional_bus:
            for _item in self.regional_bus:
                if _item:
                    _items.append(_item.to_dict())
            _dict['regional_bus'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in school_bus (list)
        _items = []
        if self.school_bus:
            for _item in self.school_bus:
                if _item:
                    _items.append(_item.to_dict())
            _dict['school_bus'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in telebus (list)
        _items = []
        if self.telebus:
            for _item in self.telebus:
                if _item:
                    _items.append(_item.to_dict())
            _dict['telebus'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in night_bus (list)
        _items = []
        if self.night_bus:
            for _item in self.night_bus:
                if _item:
                    _items.append(_item.to_dict())
            _dict['night_bus'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in ferry (list)
        _items = []
        if self.ferry:
            for _item in self.ferry:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ferry'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in interstate_train (list)
        _items = []
        if self.interstate_train:
            for _item in self.interstate_train:
                if _item:
                    _items.append(_item.to_dict())
            _dict['interstate_train'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in skybus (list)
        _items = []
        if self.skybus:
            for _item in self.skybus:
                if _item:
                    _items.append(_item.to_dict())
            _dict['skybus'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in taxi (list)
        _items = []
        if self.taxi:
            for _item in self.taxi:
                if _item:
                    _items.append(_item.to_dict())
            _dict['taxi'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V3Disruptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "general": [V3Disruption.from_dict(_item) for _item in obj["general"]] if obj.get("general") is not None else None,
            "metro_train": [V3Disruption.from_dict(_item) for _item in obj["metro_train"]] if obj.get("metro_train") is not None else None,
            "metro_tram": [V3Disruption.from_dict(_item) for _item in obj["metro_tram"]] if obj.get("metro_tram") is not None else None,
            "metro_bus": [V3Disruption.from_dict(_item) for _item in obj["metro_bus"]] if obj.get("metro_bus") is not None else None,
            "regional_train": [V3Disruption.from_dict(_item) for _item in obj["regional_train"]] if obj.get("regional_train") is not None else None,
            "regional_coach": [V3Disruption.from_dict(_item) for _item in obj["regional_coach"]] if obj.get("regional_coach") is not None else None,
            "regional_bus": [V3Disruption.from_dict(_item) for _item in obj["regional_bus"]] if obj.get("regional_bus") is not None else None,
            "school_bus": [V3Disruption.from_dict(_item) for _item in obj["school_bus"]] if obj.get("school_bus") is not None else None,
            "telebus": [V3Disruption.from_dict(_item) for _item in obj["telebus"]] if obj.get("telebus") is not None else None,
            "night_bus": [V3Disruption.from_dict(_item) for _item in obj["night_bus"]] if obj.get("night_bus") is not None else None,
            "ferry": [V3Disruption.from_dict(_item) for _item in obj["ferry"]] if obj.get("ferry") is not None else None,
            "interstate_train": [V3Disruption.from_dict(_item) for _item in obj["interstate_train"]] if obj.get("interstate_train") is not None else None,
            "skybus": [V3Disruption.from_dict(_item) for _item in obj["skybus"]] if obj.get("skybus") is not None else None,
            "taxi": [V3Disruption.from_dict(_item) for _item in obj["taxi"]] if obj.get("taxi") is not None else None
        })
        return _obj


